hl.on("hyprland.start", function()
    hl.exec_cmd("hyprctl setcursor 'Bibata-Modern-Classic' 24")
    hl.exec_cmd("dbus-update-activation-environment --systemd XCURSOR_THEME XCURSOR_SIZE HYPRCURSOR_THEME HYPRCURSOR_SIZE")
    hl.exec_cmd("mpvpaper -vs -o 'no-audio loop hwdec=auto' '*' /etc/backgrounds/gravitys-edge.mp4")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("while hyprctl activewindow >/dev/null 2>&1; do n=$(pgrep -cf '[o]rbit-shell-1.0.0/share/orbit-shell'); if [ \"$n\" -gt 1 ]; then pkill -f quickshell; sleep 2; elif [ \"$n\" = 0 ]; then orbit shell -d; sleep 6; fi; sleep 3; done")
    hl.exec_cmd("while true; do zen-apply-theme; sleep 10; done")
end)